version: '3.3'

services:
    db:
        image: postgres
        restart: always
        volumes:
            - ./tmp/pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=123
            - POSTGRES_DB=budgets
        ports:
            - 5432:5432
